name: coperception

dependencies:
  - python==3.7
  - pip
  - pip:
    - numpy
    - torch
    - opencv-python
    - torchvision
    - typing
    - nuscenes-devkit==1.0.9
    - pyquaternion
    - numba
    - matplotlib
    - mmcv
    - terminaltables
    - shapely
    - coperception